# Generated by Django 4.2.4 on 2024-09-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_alter_order_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
